name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      image_tag: |
        latest
        0.13.0-bullseye-r1 # renovate: datasource=github-releases depName=prometheus-community/postgres_exporter
        0.13.0-bullseye # renovate: datasource=github-releases depName=prometheus-community/postgres_exporter
        0.13.0 # renovate: datasource=github-releases depName=prometheus-community/postgres_exporter
        0.11
        0
    secrets: inherit
